"use strict";
const REPO_OWNER="barnaber55",REPO_NAME="NOVARISRP-",DATA_PATH="data.json",BRANCH="main";
const LOCAL_KEY="NOVARISRP_admin_draft_v1",TOKEN_KEY="NOVARISRP_GITHUB_TOKEN_SESSION";
const ADMIN_PASSWORD_HASH="bfce24cb4d09ecdbf93681071da5d7f08cbbe45608b56e1560a89255bf178133";
const MIN_ZOOM=.25,MAX_ZOOM=1.5,ZOOM_STEP=.1;
let state=null,isAdmin=false,saveTimer=null;
const $=id=>document.getElementById(id);
const els={serverName:$("serverName"),serverSubtitle:$("serverSubtitle"),saveStatus:$("saveStatus"),adminBadge:$("adminBadge"),zoomValue:$("zoomValue"),forest:$("forest"),viewport:$("treeViewport"),instructions:$("instructions"),passwordModal:$("passwordModal"),passwordInput:$("passwordInput"),passwordError:$("passwordError"),tokenModal:$("tokenModal"),tokenInput:$("tokenInput"),tokenError:$("tokenError")};
function createId(){return globalThis.crypto?.randomUUID?.()||"node-"+Date.now()+"-"+Math.random().toString(16).slice(2)}
function createNode(boxTitle,roleTitle,holderName,children=[]){return{id:createId(),boxTitle,roleTitle,holderName,players:[],children}}
function createDefaultState(){return{serverName:"NOVARISRP",serverSubtitle:"Organigramme officiel du gouvernement",zoom:.7,roots:[createNode("Présidence","Président","Nom à définir",[createNode("Ministère des Armées","Ministre des Armées","Nom à définir",[createNode("Gendarmerie","Chef gendarme","Nom à définir"),createNode("Police","Chef de la police","Nom à définir"),createNode("Armée","Chef des armées","Nom à définir")]),createNode("Ministère des Services publics","Ministre des Services publics","Nom à définir",[createNode("EMS","Chef des secours","Nom à définir"),createNode("Pompiers","Chef des pompiers","Nom à définir"),createNode("Voirie","Chef de la voirie","Nom à définir")]),createNode("Ministère des Affaires gouvernementales","Ministre des Affaires gouvernementales","Nom à définir",[createNode("Fiscalité","Chef de la fiscalité","Nom à définir"),createNode("Banque d'État","Directeur de la banque d'État","Nom à définir")])])]}}
function normalizeZoom(value){const n=Number(value);return Number.isFinite(n)?Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,n)):.7}
function normalizeNode(raw,used){raw=raw&&typeof raw==="object"?raw:{};let id=typeof raw.id==="string"&&raw.id?raw.id:createId();while(used.has(id))id=createId();used.add(id);return{id,boxTitle:typeof raw.boxTitle==="string"?raw.boxTitle:"Nouvelle case",roleTitle:typeof raw.roleTitle==="string"?raw.roleTitle:"Nouveau poste",holderName:typeof raw.holderName==="string"?raw.holderName:"Nom à définir",players:Array.isArray(raw.players)?raw.players.slice(0,200).map(v=>typeof v==="string"?v:""):[],children:Array.isArray(raw.children)?raw.children.map(c=>normalizeNode(c,used)):[]}}
function normalizeState(raw){const d=createDefaultState(),used=new Set(),roots=Array.isArray(raw?.roots)?raw.roots:(raw?.root?[raw.root]:d.roots);return{serverName:typeof raw?.serverName==="string"?raw.serverName:d.serverName,serverSubtitle:typeof raw?.serverSubtitle==="string"?raw.serverSubtitle:d.serverSubtitle,zoom:normalizeZoom(raw?.zoom),roots:roots.map(r=>normalizeNode(r,used))}}
function mark(text,mode=""){els.saveStatus.textContent=text;els.saveStatus.className="save-status"+(mode?" "+mode:"")}
async function loadOfficial(){mark("Chargement officiel…");try{const response=await fetch(DATA_PATH+"?v="+Date.now(),{cache:"no-store"});if(!response.ok)throw new Error("HTTP "+response.status);state=normalizeState(await response.json());mark("Version officielle chargée ✓","ok")}catch(error){console.error(error);state=createDefaultState();mark("Version locale de secours","error")}render()}
function saveDraft(show=false){try{localStorage.setItem(LOCAL_KEY,JSON.stringify({savedAt:Date.now(),state}));mark(show?"Brouillon enregistré ✓":"Brouillon auto ✓","ok");return true}catch(error){console.error(error);mark("Brouillon impossible","error");return false}}
function scheduleDraft(){if(!isAdmin)return;clearTimeout(saveTimer);mark("Modification non publiée…");saveTimer=setTimeout(()=>saveDraft(false),350)}
function restoreDraft(){try{const raw=localStorage.getItem(LOCAL_KEY);if(!raw)return false;const parsed=JSON.parse(raw);state=normalizeState(parsed.state||parsed);render();mark("Brouillon restauré — non publié","ok");return true}catch{return false}}
function setZoom(value,saveIt=true){state.zoom=normalizeZoom(value);els.forest.style.zoom=String(state.zoom);els.zoomValue.textContent=Math.round(state.zoom*100)+" %";if(saveIt&&isAdmin)scheduleDraft()}
function fitToScreen(){els.forest.style.zoom="1";requestAnimationFrame(()=>{const natural=Math.max(els.forest.scrollWidth,els.forest.getBoundingClientRect().width),available=Math.max(300,els.viewport.clientWidth-30);setZoom(natural>0?Math.max(MIN_ZOOM,Math.min(1,available/natural)):state.zoom,isAdmin);els.viewport.scrollLeft=0})}
function setAdminMode(enabled){isAdmin=enabled;document.querySelectorAll(".admin-only").forEach(el=>el.classList.toggle("hidden",!enabled));$("publishButton").classList.toggle("hidden",!enabled);$("loginButton").classList.toggle("hidden",enabled);els.adminBadge.classList.toggle("hidden",!enabled);els.instructions.innerHTML=enabled?"<strong>Mode administrateur :</strong> modifie puis clique sur <strong>Publier sur le site</strong> pour que tout le monde voie la nouvelle version.":"<strong>Mode visiteur :</strong> l’organigramme officiel est en lecture seule.";render()}
async function sha256(text){const bytes=new TextEncoder().encode(text),hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function tryLogin(){els.passwordError.textContent="";const value=els.passwordInput.value;if(await sha256(value)!==ADMIN_PASSWORD_HASH){els.passwordError.textContent="Mot de passe incorrect.";return}els.passwordInput.value="";els.passwordModal.classList.add("hidden");setAdminMode(true);restoreDraft()}
function logout(){setAdminMode(false);sessionStorage.removeItem(TOKEN_KEY);mark("Mode visiteur","ok")}
function textInput(cls,value,label,onInput){const input=document.createElement("input");input.type="text";input.className="field "+cls;input.value=value;input.disabled=!isAdmin;input.setAttribute("aria-label",label);input.addEventListener("input",()=>{if(!isAdmin)return;onInput(input.value);scheduleDraft()});return input}
function locateInChildren(id,parent){for(let i=0;i<parent.children.length;i++){const child=parent.children[i];if(child.id===id)return{node:child,collection:parent.children,index:i};const nested=locateInChildren(id,child);if(nested)return nested}return null}
function locateNode(id){for(let i=0;i<state.roots.length;i++){const root=state.roots[i];if(root.id===id)return{node:root,collection:state.roots,index:i};const nested=locateInChildren(id,root);if(nested)return nested}return null}
function updatePlayerCount(node,value){if(!isAdmin)return;let n=parseInt(value,10);n=Number.isFinite(n)?Math.max(0,Math.min(200,n)):0;while(node.players.length<n)node.players.push("Joueur "+(node.players.length+1));if(node.players.length>n)node.players.splice(n);saveDraft();render()}
function addPresident(){if(!isAdmin)return;state.roots.push(createNode("Présidence","Président","Nom à définir"));saveDraft();render()}
function addChild(parentId){if(!isAdmin)return;const loc=locateNode(parentId);if(!loc)return;loc.node.children.push(createNode("Nouvelle case","Nouveau poste","Nom à définir"));saveDraft();render()}
function countDescendants(node){return node.children.reduce((total,child)=>total+1+countDescendants(child),0)}
function deleteNode(id){if(!isAdmin)return;const loc=locateNode(id);if(!loc)return;const d=countDescendants(loc.node),msg=d?'Supprimer « '+loc.node.boxTitle+' » et ses '+d+' sous-case(s) ?':'Supprimer « '+loc.node.boxTitle+' » ?';if(!confirm(msg))return;const fresh=locateNode(id);if(!fresh)return;fresh.collection.splice(fresh.index,1);saveDraft();render()}
function moveNode(id,direction){if(!isAdmin)return;const loc=locateNode(id);if(!loc)return;const target=loc.index+direction;if(target<0||target>=loc.collection.length)return;const moved=loc.collection.splice(loc.index,1)[0];loc.collection.splice(target,0,moved);saveDraft();render()}
function renderPlayers(node){if(!node.players.length){const e=document.createElement("div");e.className="players-empty";e.textContent="0 joueur dans cette case";return e}const players=document.createElement("div");players.className="players";node.players.forEach((name,index)=>{const row=document.createElement("div");row.className="player-row";const number=document.createElement("div");number.className="player-number";number.textContent=String(index+1).padStart(2,"0");row.append(number,textInput("player-input",name,"Nom du joueur",value=>node.players[index]=value));players.append(row)});return players}
function button(text,cls,handler){const b=document.createElement("button");b.type="button";b.className=cls;b.textContent=text;b.onclick=handler;return b}
function renderNode(node,isRoot){const branch=document.createElement("div");branch.className="branch";branch.dataset.nodeId=node.id;const card=document.createElement("article");card.className="node-card"+(isRoot?" root":"");const header=document.createElement("div");header.className="node-header";const type=document.createElement("div");type.className="node-type";type.textContent=isRoot?"Président / sommet":"Poste dépendant";header.append(type,textInput("box-title",node.boxTitle,"Nom de la case",v=>node.boxTitle=v),textInput("role-title",node.roleTitle,"Nom du poste",v=>node.roleTitle=v),textInput("holder-name",node.holderName,"Nom de la personne",v=>node.holderName=v));const body=document.createElement("div");body.className="node-body";const control=document.createElement("div");control.className="player-control";const label=document.createElement("label");label.className="control-label";label.innerHTML="Nombre de joueurs<span>0 à 200</span>";const count=document.createElement("input");count.type="number";count.className="count-input";count.min="0";count.max="200";count.value=String(node.players.length);count.disabled=!isAdmin;count.onchange=()=>updatePlayerCount(node,count.value);control.append(label,count);body.append(control,renderPlayers(node));card.append(header,body);if(isAdmin){const actions=document.createElement("div");actions.className="node-actions";actions.append(button("＋ Ajouter une case dessous","button primary add-child",()=>addChild(node.id)),button("← Gauche","button",()=>moveNode(node.id,-1)),button("Droite →","button",()=>moveNode(node.id,1)),button(isRoot?"🗑 Supprimer ce président":"🗑 Supprimer ce poste","button danger delete-node",()=>deleteNode(node.id)));card.append(actions)}branch.append(card);if(node.children.length){const children=document.createElement("div");children.className="children";node.children.forEach(child=>children.append(renderNode(child,false)));branch.append(children)}return branch}
function render(){if(!state)return;els.serverName.value=state.serverName;els.serverSubtitle.value=state.serverSubtitle;els.serverName.disabled=!isAdmin;els.serverSubtitle.disabled=!isAdmin;els.forest.replaceChildren();if(!state.roots.length){const empty=document.createElement("div");empty.className="empty-state";empty.innerHTML="<strong>Aucun président</strong>Connecte-toi en administrateur pour en ajouter un.";els.forest.append(empty)}else state.roots.forEach(root=>els.forest.append(renderNode(root,true)));setZoom(state.zoom,false)}
function utf8ToBase64(text){const bytes=new TextEncoder().encode(text);let binary="";const chunk=8192;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(binary)}
async function publishWithToken(token){els.tokenError.textContent="";mark("Publication GitHub…");const api=`https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${DATA_PATH}`;try{const common={"Accept":"application/vnd.github+json","Authorization":"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28"};const current=await fetch(api+"?ref="+encodeURIComponent(BRANCH),{headers:common,cache:"no-store"});if(!current.ok)throw new Error(current.status===401?"Clé GitHub invalide.":current.status===403?"La clé n’a pas l’autorisation Contents: Read and write.":"Lecture GitHub impossible ("+current.status+").");const info=await current.json();const json=JSON.stringify(state,null,2);const update=await fetch(api,{method:"PUT",headers:{...common,"Content-Type":"application/json"},body:JSON.stringify({message:"Met à jour la hiérarchie NOVARISRP",content:utf8ToBase64(json),sha:info.sha,branch:BRANCH})});if(!update.ok){let detail="";try{detail=(await update.json()).message||""}catch{}throw new Error("Publication refusée ("+update.status+") "+detail)}sessionStorage.setItem(TOKEN_KEY,token);localStorage.removeItem(LOCAL_KEY);els.tokenModal.classList.add("hidden");els.tokenInput.value="";mark("Publié pour tout le monde ✓","ok");alert("Hiérarchie publiée sur GitHub. GitHub Pages peut mettre environ 1 à 2 minutes à afficher la nouvelle version.")}catch(error){console.error(error);els.tokenError.textContent=error.message;mark("Publication échouée","error")}}
function requestPublish(){if(!isAdmin)return;const token=sessionStorage.getItem(TOKEN_KEY);if(token){publishWithToken(token);return}els.tokenModal.classList.remove("hidden");setTimeout(()=>els.tokenInput.focus(),50)}
function exportJson(){saveDraft();const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="NOVARISRP-data.json";a.click();URL.revokeObjectURL(url)}
function importJson(file){const reader=new FileReader();reader.onload=e=>{try{state=normalizeState(JSON.parse(String(e.target.result)));saveDraft(true);render()}catch{alert("Le fichier JSON est invalide.")}};reader.readAsText(file,"utf-8")}
els.serverName.addEventListener("input",e=>{if(isAdmin){state.serverName=e.target.value;scheduleDraft()}});els.serverSubtitle.addEventListener("input",e=>{if(isAdmin){state.serverSubtitle=e.target.value;scheduleDraft()}});
$("zoomOutButton").onclick=()=>setZoom(state.zoom-ZOOM_STEP);$("zoomInButton").onclick=()=>setZoom(state.zoom+ZOOM_STEP);$("fitButton").onclick=fitToScreen;$("loginButton").onclick=()=>{els.passwordModal.classList.remove("hidden");els.passwordError.textContent="";setTimeout(()=>els.passwordInput.focus(),50)};$("cancelPassword").onclick=()=>els.passwordModal.classList.add("hidden");$("validatePassword").onclick=tryLogin;els.passwordInput.addEventListener("keydown",e=>{if(e.key==="Enter")tryLogin()});$("logoutButton").onclick=logout;$("publishButton").onclick=requestPublish;$("addPresidentButton").onclick=addPresident;$("draftButton").onclick=()=>saveDraft(true);$("exportButton").onclick=exportJson;$("importButton").onclick=()=>$("importFile").click();$("importFile").onchange=e=>{const file=e.target.files?.[0];if(file)importJson(file);e.target.value=""};$("resetButton").onclick=()=>{if(confirm("Réinitialiser le brouillon ?")){state=createDefaultState();saveDraft(true);render()}};$("cancelToken").onclick=()=>els.tokenModal.classList.add("hidden");$("validateToken").onclick=()=>{const token=els.tokenInput.value.trim();if(!token){els.tokenError.textContent="Entre la clé GitHub.";return}publishWithToken(token)};els.tokenInput.addEventListener("keydown",e=>{if(e.key==="Enter")$("validateToken").click()});els.viewport.addEventListener("wheel",e=>{if(!e.ctrlKey)return;e.preventDefault();setZoom(state.zoom+(e.deltaY>0?-ZOOM_STEP:ZOOM_STEP),isAdmin)},{passive:false});
loadOfficial();
